# Generated by Django 4.1.4 on 2023-03-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expenses_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
