# Generated by Django 4.1.4 on 2023-02-07 18:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('CATEGORY', models.CharField(blank=True, choices=[('am', 'Automotive'), ('re', 'Real Estate'), ('jb', 'Job'), ('hg', 'House and Garden'), ('ec', 'Electronics'), ('fa', 'Fashion'), ('sp', 'Sport'), ('ot', 'Other')], default='ot', max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('photo', models.ImageField(blank=True, default='media/blank.jpg', upload_to='marketplace/')),
                ('date', models.DateField(db_index=True, default=datetime.date.today)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-pk'),
            },
        ),
    ]
