# Generated by Django 4.1.4 on 2023-02-08 18:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_rename_category_auction_category_alter_auction_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='slug_name',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='photo',
            field=models.ImageField(blank=True, default='/blank/blank.jpg', upload_to='marketplace/'),
        ),
    ]
