# Generated by Django 4.1.4 on 2023-02-08 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auction_slug_name_alter_auction_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='slug_name',
            new_name='slug',
        ),
    ]
