# Generated by Django 4.1.4 on 2023-02-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, to='marketplace.auction'),
        ),
    ]
